- name: setup to assume role
  sts_assume_role:
    role_arn: "arn:aws:iam::872347420764:role/provisionSecurityGroup"
    role_session_name: "EC2AutmatedProvisioning"
    region: "{{ AWSDefaultRegion }}"
  register: assumed_role

- include: clean-vpc.yml
  when: CleanupVPC == "true"

- include: vpc-build.yml 

- include: gateway-build.yml

- include: snapshot.yml
