
    - name: build primary vpc 
      ec2_vpc:
        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"
        region: "{{ AWSDefaultRegion }}"
        state: present
        cidr_block: "{{VPCDevCIDR}}"
        resource_tags: {"Name":"{{VPCEnvironment}}", "InstanceType": "VPC","Environment":"{{VPCEnvironment}}" }
      register: vpc

    - debug:
        msg: "{{vpc}}"

    - name: build subnets
      ec2_vpc_subnet:
        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"
        region: "{{ AWSDefaultRegion }}"
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ item.SubnetCIDR }}"
        az: "{{AWSAvailZoneOpt1}}"
        resource_tags: {"Name":"{{item.SubnetCat}}-{{AWSAvailZoneOpt1}}","InstanceType": "Subnet","Environment":"{{VPCEnvironment}}", "SubnetCat":"{{item.SubnetCat}}", "WebGateway":"{{item.Internet}}"}
      register: database_subnet
      with_items:
        "{{AWSSubnetAZ1}}"
      register: devSubnets



