
    - name: build primary vpc 
      ec2_vpc:
        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"
        region: "{{ AWSDefaultRegion }}"
        state: present
        cidr_block: "{{VPCDevCIDR}}"
        resource_tags: { "InstanceType": "VPC","Environment":"{{VPCEnvironment}}" }
      register: vpc

    - name: build subnets
      ec2_vpc_subnet:
        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"
        region: "{{ AWSDefaultRegion }}"
        state: present
        vpc_id: "{{ vpc.vpc_id }}"
        cidr: "{{ item.SubnetCIDR }}"
        resource_tags: { "InstanceType": "Subnet","Environment":"{{VPCEnvironment}}", "SubnetCat":"{{item.SubnetCat}}", "WebGateway":"{{item.Internet}}"}
      register: database_subnet
      with_items:
        - { SubnetCat: Base, SubnetCIDR: 172.22.0.0/20, Internet: Connected }
        - { SubnetCat: Database, SubnetCIDR: 172.22.32.0/20, Internet: NotConnected }
        - { SubnetCat: Integration, SubnetCIDR: 172.22.80.0/20, Internet: Connected }
        - { SubnetCat: Monitoring, SubnetCIDR:  172.22.96.0/20, Internet: Not Connected }
      register: devSubnets



