    - name: setup to assume role
      sts_assume_role:
        role_arn: "arn:aws:iam::872347420764:role/provisionSecurityGroup"
        role_session_name: "EC2AutmatedProvisioning"
        region: "{{ AWSDefaultRegion }}"
      register: assumed_role

    - name: build primary vpc 
      ec2_vpc:
        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"
        region: "{{ AWSDefaultRegion }}"
        state: present
        cidr_block: "{{VPCDevCIDR}}"
        resource_tags: { "InstanceType": "VPC","Environment":"{{VPCEnvironment}}" }
      register: vpc

    - name: build subnets
      ec2_vpc_subnet:
        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"
        region: "{{ AWSDefaultRegion }}"
        state: present
        vpc_id: "{{ vpc.vpc_id }}"
        cidr: "{{ item.SubnetCIDR }}"
        resource_tags: { "InstanceType": "Subnet","Environment":"{{VPCEnvironment}}", "SubnetCat":"{{item.SubnetCat}}"}
      register: database_subnet
      with_items:
        - { SubnetCat: Base, SubnetCIDR: 172.22.0.0/20}
        - { SubnetCat: Database, SubnetCIDR: 172.22.32.0/20}
        - { SubnetCat: Integration, SubnetCIDR: 172.22.80.0/20}
        - { SubnetCat: Monitoring, SubnetCIDR:  172.22.96.0/20}
      register: devSubnets

    - debug:
        msg: "{{ devSubnets }}"

    - name: Getting subnet facts
      ec2_vpc_subnet_facts:
        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"
        region: "{{ AWSDefaultRegion }}"
        filters:
          "tag:SubnetCat": Base
      register: baseSubnet

    - debug:
        msg: "{{ baseSubnet }}"


